services:
  task-manager-keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    container_name: task-manager-keycloak
    restart: always
    ports:
      - "${KEYCLOAK_PORT}:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: task-manager-keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    command: ["start-dev"]
    depends_on:
      - task-manager-keycloak-db
  task-manager-keycloak-db:
    image: postgres:15
    container_name: task-manager-keycloak-db
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
  task-manager-users-db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${USER_DB_NAME}
    ports:
      - '${USER_DB_PORT}:5432'
  task-manager-calendar-db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${CALENDAR_DB_NAME}
    ports:
      - '${CALENDAR_DB_PORT}:5432'
  task-manager-knowledge-db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${KNOWLEDGE_DB_NAME}
    ports:
      - '${KNOWLEDGE_DB_PORT}:5432'
  task-manager-project-db:
    image: postgres:14.3
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${PROJECT_DB_NAME}
    ports:
      - '${PROJECT_DB_PORT}:5432'
  task-manager-zookeeper:
    image: wurstmeister/zookeeper
    container_name: task-manager-zookeeper
  task-manager-kafka:
    image: wurstmeister/kafka
    container_name: task-manager-kafka
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: task-manager-zookeeper:2181
  task-manager-redis:
    image: redis:4.0.5-alpine
    ports:
      - "${REDIS_PORT}:6379"
  task-manager-mongo:
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodata:/data/db
volumes:
  keycloak-db-data:
  mongodata:
    driver: local